23-active-record/chinook_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tracks#index"
  get "/tracks",  to: 'tracks#index'
  get "/search", to: 'tracks#search', :as =>  "search_page"
end

23-active-record/chinook_app/app/models/album.rb
class Album < ApplicationRecord
end

23-active-record/chinook_app/app/models/artist.rb
class Artist < ApplicationRecord
end

23-active-record/chinook_app/app/models/genre.rb
class Genre < ApplicationRecord
end

23-active-record/chinook_app/app/models/media_type.rb
class MediaType < ApplicationRecord
end

23-active-record/chinook_app/app/models/playlist.rb
class Playlist < ApplicationRecord
end

23-active-record/chinook_app/app/models/track.rb
class Track < ApplicationRecord

    SHORT = 180000
    LONG = 360000

    scope :name_strats_with, -> (name){ where("name ILIKE ?", "#{name}%") }


    scope :short, -> { shorter_than(SHORT) }
    scope :long, -> { longer_than_or_equal_to (LONG) }
    scope :medium, -> { longer_than_or_equal_to(SHORT).shorter_than(LONG) }
    scope :starts_with, -> (char) { where('name ILIKE ?', "#{char}%") }

    scope :shorter_than, -> (milliseconds){
        where('milliseconds < ?', milliseconds)  if(milliseconds && milliseconds > 0)
    }

    scope :longer_than_or_equal_to, -> (milliseconds){
        where('milliseconds >= ? ', milliseconds)  if(milliseconds && milliseconds > 0)
    }

    # scope :shorter_than, -> (milliseconds){
    #     if(milliseconds && milliseconds > 0)
    #         where('milliseconds < ?', milliseconds)
    #     end
    # }




    # def self.shorter_than(milliseconds)
    #     if(milliseconds && milliseconds > 0)
    #         where('milliseconds < ?', milliseconds)
    #     else
    #         all
    #     end
    # end

    # def self.longer_than_or_equal_to(milliseconds)
    #     where('milliseconds >= ? ', milliseconds)
    # end

    
    # def self.starts_with(char)
    #     where('name ILIKE ?', "#{char}%")
    # end

    # def self.short
    #     # where('milliseconds < ?', SHORT)
    #     shorter_than(SHORT)
    # end

    # def self.long
    #     # where('milliseconds >= ? ', LONG)
    #     longer_than_or_equal_to((LONG))
    # end

    # def self.medium
    #     # where('millisecond >= ?', SHORT).where('milliseconds < ?', LONG)
    #     longer_than_or_equal_to(SHORT).shorter_than(LONG)
    # end

   
end

23-active-record/chinook_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    def index
        @tracks = Track.all
    end

    def search
        @tracks = Track.name_strats_with(params[:search])
    end
end

23-active-record/chinook_app/app/helpers/tracks_helper.rb
module TracksHelper
end

23-active-record/chinook_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChinookApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

23-active-record/chinook_app/app/views/tracks/index.html.erb
<h1>welcome to the home page</h1>

<h2>you have <%= @tracks.count %> number of tracks</h2>


<%= form_tag(search_page_path, :method => "get") do %>   
    <%= search_field_tag :search, params[:search], placeholder: "starts with" %>   
      <%= button_tag "search", :name => nil%>  

<% end %>
  
  

23-active-record/chinook_app/app/views/tracks/search.html.erb
<h1>this the show page</h1>
<%= link_to "home", root_path %>
<h2>there are <%= @tracks.count %> that equal your search</h2>

<ul>

<% @tracks.each do |t| %>
    <li><%= t.name %></li>
<% end %>


</ul>