20-contactbook/firstRailsApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/contacts' => "contacts#index"
  # get '/contacts/new' => "contacts#new"
  # get '/contacts/:id' => "contacts#show"

  # post '/contacts' => "contacts#create"

  # get '/contacts/:id/edit' => 'contacts#edit'
  # patch '/contacts/:id' => 'contacts#update' , as: "contact"

  # delete '/contacts/:id' => 'contacts#destroy'

  root 'contacts#index'

  resources :contacts
  
end

20-contactbook/firstRailsApp/app/models/contact.rb
class Contact < ApplicationRecord

    def full_name
        return fname+" "+lname
    end
end

20-contactbook/firstRailsApp/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

    def index
        @contacts = Contact.all
    end

    def show
        @contact = Contact.find(params[:id])
    end

    def create
        @contact = Contact.new(contact_params) 
        # @contact.fname = params[:contact][:fname]
        # @contact.lname = params[:contact][:lname]
        # @contact.email = params[:contact][:email]
        # @contact.notes = params[:contact][:notes]

        if @contact.save 
            redirect_to contacts_url
        else 
            render :new
        end

        #    render plain: "In the create method #{params}" 
    end

    def new
        @contact = Contact.new
    end

    def edit
        @contact = Contact.find(params[:id])
    end

    def update
        @contact = Contact.find(params[:id])

        if @contact.update(contact_params)
            redirect_to contact_url
        else 
            render :edit
        end
    end

    def destroy
        @contact = Contact.find(params[:id])
        @contact.destroy
        redirect_to contacts_url
    end

    private
    def contact_params
        params.require(:contact).permit(:fname, :lname, :email, :notes)
    end

    
end

20-contactbook/firstRailsApp/app/helpers/contacts_helper.rb
module ContactsHelper
end

20-contactbook/firstRailsApp/app/views/contacts/edit.html.erb
<h1>You can edit a contact</h1>
<%= form_for (@contact) do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :fname %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :lname %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>
  <%= f.submit %>
<%end%>

20-contactbook/firstRailsApp/app/views/contacts/index.html.erb
<h1>Helloooooo </h1>
<ul>
  <% @contacts.each do |c| %>
    <li> <%= c.fname %> | <%= link_to "Delete this contact", contact_path(c) , method: :delete, data: {confirm: "Are you sure ?? "} %> | 
      <%= link_to "Edit", edit_contact_path(c) %>
    </li>
  <% end %>
</ul>


<%= link_to "Add a contact", new_contact_path %>

20-contactbook/firstRailsApp/app/views/contacts/new.html.erb
<h1>You can create a contact</h1>
<%= form_for (@contact) do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :fname %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :lname %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>
  <%= f.submit %>
<%end%>

20-contactbook/firstRailsApp/app/views/contacts/show.html.erb
<h1>Welcome to my contact</h1>
<div>
  <p> <%= @contact.fname %></p>
  <p> <%= @contact.lname %></p>
  <p> <%= @contact.email %></p>
  <p> <%= @contact.notes %></p>
</div>

20-contactbook/firstRailsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>