21-rails-routes/photoLab/config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "photos#index"
  get "/home" => "home#welcome" , as: "home_page"
  get "/about_us" => "home#about", as: "about"

  
  # resources :photos, only: [:index, :show]
  resources :photos, except: [:destroy]
end

21-rails-routes/photoLab/app/models/photo.rb
class Photo < ApplicationRecord
end

21-rails-routes/photoLab/app/controllers/home_controller.rb
class HomeController < ApplicationController

    def welcome
        @message = "Welcome to my web app"
    end

    def about
        @about = "I am a programmer"
        render :hello
    end
end

21-rails-routes/photoLab/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
    @photo = Photo.new
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
  end

  def update
  end

  def destroy
  end
end

21-rails-routes/photoLab/app/helpers/home_helper.rb
module HomeHelper
end

21-rails-routes/photoLab/app/helpers/photos_helper.rb
module PhotosHelper
end

21-rails-routes/photoLab/app/views/home/hello.html.erb
<h1><%= @about %></h1>

21-rails-routes/photoLab/app/views/home/welcome.html.erb
<h1><%= @message %></h1>

21-rails-routes/photoLab/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoLab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav>
      <div>
        <%= link_to "Home", home_page_path %>
      </div>
      <div>
        <%= link_to "About us", about_path %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

21-rails-routes/photoLab/app/views/photos/_form.html.erb
<%= form_for newPhoto do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

21-rails-routes/photoLab/app/views/photos/edit.html.erb
<h1>Photos#edit</h1>
<p>Find me in app/views/photos/edit.html.erb</p>

<%= render partial: "form", locals:{ newPhoto: @photo} %>

21-rails-routes/photoLab/app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

<%= render partial: "form", locals:{ newPhoto: @photo} %>

21-rails-routes/photoLab/app/views/photos/new.html.erb
<h1>Photos#new</h1>
<p>Find me in app/views/photos/new.html.erb</p>

<%= render partial: "form", locals:{ newPhoto: @photo} %>

21-rails-routes/photoLab/app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>