24-associations/inClass/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pictures#index'
  resources :pictures
end

24-associations/inClass/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

24-associations/inClass/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :picture
end

24-associations/inClass/app/models/picture.rb
class Picture < ApplicationRecord
    has_many :comments

    has_and_belongs_to_many :tags
end

24-associations/inClass/app/models/tag.rb
class Tag < ApplicationRecord

    has_and_belongs_to_many :pictures
end

24-associations/inClass/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

24-associations/inClass/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    
  def create
    @picture = Picture.new
    @picture.title = params[:picture][:title]
    @picture.description = params[:picture][:description]
    @picture.url = params[:picture][:url]

    if @picture.save
      redirect_to pictures_path
    else
      render :new
    end
  end

  def new
    @picture = Picture.new
  end

  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
    @comments = @picture.comments
    @tags = @picture.tags
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    @picture.title = params[:picture][:title]
    @picture.description = params[:picture][:description]
    @picture.url = params[:picture][:url]

    if @picture.save
      redirect_to picture_path(@picture)
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    if @picture.destroy
      redirect_to pictures_path
    else
      render :show
    end
  end
end

24-associations/inClass/app/helpers/application_helper.rb
module ApplicationHelper
end

24-associations/inClass/app/helpers/pictures_helper.rb
module PicturesHelper
end

24-associations/inClass/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InClass</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <h1><%= link_to 'Photo lab', root_path %></h1>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

24-associations/inClass/app/views/pictures/edit.html.erb
<h2> Edit picture <%= @picture.id %> </h2>
<%= form_for @picture do |f| %>
  <div class="field">
    <p><%= f.label :title %></p>
    <p><%= f.text_field :title %></p>
  </div>

  <div class="field">
    <p><%= f.label :description %></p>
    <p><%= f.text_field :description %></p>
  </div>

  <div class="field">
    <p><%= f.label :url %></p>
    <p><%= f.text_field :url %></p>
  </div>

  <div class="field">
    <p><%= f.submit  %></p>
  </div>
<% end %>

24-associations/inClass/app/views/pictures/index.html.erb
<%= link_to "Add new picture", new_picture_path %>

<section class="pictures">
  <% @pictures.each do |picture| %>
    <section class="picture">
      <p> <%= link_to 'View', picture_path(picture) %> <%= link_to 'Edit', edit_picture_path(picture) %> <%= link_to 'Delete', picture_path(picture), method: :delete, data: {confirm: "Are you sure?" } %> </p>
      <p class="picture-title"> <%= picture.title %> </p>
      <p class="description"> <%= picture.description %> </p>
      <p class="description"> Picture has <%= picture.comments.size %> comments </p>
      <div class="image-frame"><%= link_to image_tag(picture.url), picture_path(picture) %></div>
    </section>
  <% end %>
</section>

24-associations/inClass/app/views/pictures/new.html.erb
<h2> New picture </h2>
<%= form_for @picture do |f| %>
  <div class="field">
    <p><%= f.label :title %></p>
    <p><%= f.text_field :title %></p>
  </div>

  <div class="field">
    <p><%= f.label :description %></p>
    <p><%= f.text_field :description %></p>
  </div>

  <div class="field">
    <p><%= f.label :url %></p>
    <p><%= f.text_field :url %></p>
  </div>

  <div class="field">
    <p><%= f.submit  %></p>
  </div>
<% end %>

24-associations/inClass/app/views/pictures/show.html.erb
<section class="show-picture">
  <p> <%= link_to 'Edit', edit_picture_path(@picture) %> <%= link_to 'Delete', picture_path(@picture), method: :delete, data: {confirm: "Are you sure?" } %> </p>
  <p> <%= @picture.title %> </p>
  <p> <%= @picture.description %> </p>
  <%= image_tag @picture.url %>

</section>

<div>
<h2>Comments</h2>
<ul>
   <% @comments.each do |comment| %>
    <li><p><%= comment.name %> said <%= comment.message %> </p>
    <p> on <%= comment.created_at %></p>
    
    </li>
    <%end %>
</ul>
</div>

<h2>Tags</h2>
<ul>
   <% @tags.each do |tag| %>
    <li><p><%= tag.name %> </p>
    
    </li>
    <%end %>
</ul>
</div>